# DO NOT EDIT THIS FILE!
#
# Python module Demo__POA generated by omniidl

import omniORB
omniORB.updateModule("Demo__POA")

# ** 1. Stub files contributing to this module
import Calculator_idl

# ** 2. Sub-modules

# ** 3. End
