# DO NOT EDIT THIS FILE!
#
# Python module Basic_Demo generated by omniidl

import omniORB
omniORB.updateModule("Basic_Demo")

# ** 1. Stub files contributing to this module
import Basic_Demo_idl

# ** 2. Sub-modules

# ** 3. End
