// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "Calculator.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



Demo::Calculator_ptr Demo::Calculator_Helper::_nil() {
  return ::Demo::Calculator::_nil();
}

::CORBA::Boolean Demo::Calculator_Helper::is_nil(::Demo::Calculator_ptr p) {
  return ::CORBA::is_nil(p);

}

void Demo::Calculator_Helper::release(::Demo::Calculator_ptr p) {
  ::CORBA::release(p);
}

void Demo::Calculator_Helper::marshalObjRef(::Demo::Calculator_ptr obj, cdrStream& s) {
  ::Demo::Calculator::_marshalObjRef(obj, s);
}

Demo::Calculator_ptr Demo::Calculator_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Demo::Calculator::_unmarshalObjRef(s);
}

void Demo::Calculator_Helper::duplicate(::Demo::Calculator_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

Demo::Calculator_ptr
Demo::Calculator::_duplicate(::Demo::Calculator_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

Demo::Calculator_ptr
Demo::Calculator::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Demo::Calculator_ptr
Demo::Calculator::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Demo::Calculator_ptr
Demo::Calculator::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Calculator _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Calculator* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Calculator;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Demo::Calculator::_PD_repoId = "IDL:Demo/Calculator:1.0";


Demo::_objref_Calculator::~_objref_Calculator() {
  
}


Demo::_objref_Calculator::_objref_Calculator(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Demo::Calculator::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
Demo::_objref_Calculator::_ptrToObjRef(const char* id)
{
  if (id == ::Demo::Calculator::_PD_repoId)
    return (::Demo::Calculator_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::Demo::Calculator::_PD_repoId))
    return (::Demo::Calculator_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for Demo::Calculator::add

// Proxy call descriptor class. Mangled signature:
//  _cfloat_i_cfloat_i_cfloat
class _0RL_cd_a94663619a34073f_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a94663619a34073f_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Float arg_0;
  ::CORBA::Float arg_1;
  ::CORBA::Float result;
};

void _0RL_cd_a94663619a34073f_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_a94663619a34073f_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Float&)arg_0 <<= _n;
  (::CORBA::Float&)arg_1 <<= _n;

}

void _0RL_cd_a94663619a34073f_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_a94663619a34073f_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Float&)result <<= _n;

}

const char* const _0RL_cd_a94663619a34073f_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_a94663619a34073f_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a94663619a34073f_00000000* tcd = (_0RL_cd_a94663619a34073f_00000000*)cd;
  Demo::_impl_Calculator* impl = (Demo::_impl_Calculator*) svnt->_ptrToInterface(Demo::Calculator::_PD_repoId);
  tcd->result = impl->add(tcd->arg_0, tcd->arg_1);


}

::CORBA::Float Demo::_objref_Calculator::add(::CORBA::Float a, ::CORBA::Float b)
{
  _0RL_cd_a94663619a34073f_00000000 _call_desc(_0RL_lcfn_a94663619a34073f_10000000, "add", 4);
  _call_desc.arg_0 = a;
  _call_desc.arg_1 = b;

  _invoke(_call_desc);
  return _call_desc.result;


}

Demo::_pof_Calculator::~_pof_Calculator() {}


omniObjRef*
Demo::_pof_Calculator::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::Demo::_objref_Calculator(ior, id);
}


::CORBA::Boolean
Demo::_pof_Calculator::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::Demo::Calculator::_PD_repoId))
    return 1;
  
  return 0;
}

const Demo::_pof_Calculator _the_pof_Demo_mCalculator;

Demo::_impl_Calculator::~_impl_Calculator() {}


::CORBA::Boolean
Demo::_impl_Calculator::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "add")) {

    _0RL_cd_a94663619a34073f_00000000 _call_desc(_0RL_lcfn_a94663619a34073f_10000000, "add", 4, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
Demo::_impl_Calculator::_ptrToInterface(const char* id)
{
  if (id == ::Demo::Calculator::_PD_repoId)
    return (::Demo::_impl_Calculator*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::Demo::Calculator::_PD_repoId))
    return (::Demo::_impl_Calculator*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
Demo::_impl_Calculator::_mostDerivedRepoId()
{
  return ::Demo::Calculator::_PD_repoId;
}

POA_Demo::Calculator::~Calculator() {}

