# DO NOT EDIT THIS FILE!
#
# Python module Advanced_Demo__POA generated by omniidl

import omniORB
omniORB.updateModule("Advanced_Demo__POA")

# ** 1. Stub files contributing to this module
import QA_idl

# ** 2. Sub-modules

# ** 3. End
