// This file is generated by omniidl (C++ backend)- omniORB_4_3. Do not edit.
#ifndef __Basic__Demo_hh__
#define __Basic__Demo_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_Basic__Demo
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_Basic__Demo
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_Basic__Demo
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE Basic_Demo

_CORBA_MODULE_BEG

#ifndef __Basic__Demo_mAdd__Operator__
#define __Basic__Demo_mAdd__Operator__
  class Add_Operator;
  class _objref_Add_Operator;
  class _impl_Add_Operator;
  
  typedef _objref_Add_Operator* Add_Operator_ptr;
  typedef Add_Operator_ptr Add_OperatorRef;

  class Add_Operator_Helper {
  public:
    typedef Add_Operator_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Add_Operator, Add_Operator_Helper> Add_Operator_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Add_Operator,Add_Operator_Helper > Add_Operator_out;

#endif

  // interface Add_Operator
  class Add_Operator {
  public:
    // Declarations for this interface type.
    typedef Add_Operator_ptr _ptr_type;
    typedef Add_Operator_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Add_Operator :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Float add(::CORBA::Float a, ::CORBA::Float b);

    // Constructors
    inline _objref_Add_Operator()  { _PR_setobj(0); }  // nil
    _objref_Add_Operator(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Add_Operator();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Add_Operator(const _objref_Add_Operator&);
    _objref_Add_Operator& operator = (const _objref_Add_Operator&);
    // not implemented

    friend class Add_Operator;
  };

  class _pof_Add_Operator : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Add_Operator() : _OMNI_NS(proxyObjectFactory)(Add_Operator::_PD_repoId) {}
    virtual ~_pof_Add_Operator();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Add_Operator :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Add_Operator();

    virtual ::CORBA::Float add(::CORBA::Float a, ::CORBA::Float b) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_Basic_Demo
_CORBA_MODULE_BEG

  class Add_Operator :
    public virtual Basic_Demo::_impl_Add_Operator,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Add_Operator();

    inline ::Basic_Demo::Add_Operator_ptr _this() {
      return (::Basic_Demo::Add_Operator_ptr) _do_this(::Basic_Demo::Add_Operator::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_Basic_Demo
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
Basic_Demo::Add_Operator::_marshalObjRef(::Basic_Demo::Add_Operator_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_Basic__Demo
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_Basic__Demo
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_Basic__Demo
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_Basic__Demo
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_Basic__Demo
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_Basic__Demo
#endif

#endif  // __Basic__Demo_hh__

