# DO NOT EDIT THIS FILE!
#
# Python module Demo generated by omniidl

import omniORB
omniORB.updateModule("Demo")

# ** 1. Stub files contributing to this module
import Calculator_idl

# ** 2. Sub-modules

# ** 3. End
